// 生成物，不要手改。由 tools/make-i18n.py 从 src/core/Quirks.cpp 的表生成。
//
// 存在的唯一理由是让 lupdate 扫得到故障注入表里的字串 —— 那张表是数据、
// 不经过 tr()，而界面（QuirksTab）显示前会经 gui/I18n.h 查一次译文。
// 改了 quirk 之后跑一遍 tools/make-i18n.py 再跑 lupdate，
// 否则 tst_i18n 会因为缺英文译文而失败。

#include "core/QuirkStrings.h"

#include <QtCore/QCoreApplication>

namespace onvifsim {

QStringList quirkTranslatableStrings()
{
    return {
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "发现")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "WS-Discovery 命名空间方言")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "默认照抄 Probe 的命名空间回复。参照客户端用 1.0 方言（2005/04 discovery + 2004/08 addressing），ONVIF 另一常见方言是 2009/01；强制成客户端不认的那套即可复现「搜不到设备」。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "echo=照抄 Probe，2005=强制 1.0，2009=强制 OASIS")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "ProbeMatch 不带 XAddrs")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端收到空 XAddrs 会自动多播 Resolve 补问，用来验证 Resolve 分支。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "ProbeMatch 缺 MetadataVersion")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "wsdiscovery 2.1.2 解析 ProbeMatch 时缺这个字段会把整包丢掉，设备直接消失。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "XAddrs 放不可达地址")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端只取 getXAddrs()[0]，把坏地址放第一位就能测它的容错。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "要插入的 host，可填 0.0.0.0 或主机名")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "放在 XAddrs 第一位")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不回 ProbeMatch")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "设备在线但不应答发现，客户端只能手工填 IP。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "延迟回复 ProbeMatch")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "wsdiscovery 的 searchServices 是「发 Probe → sleep timeout → 收结果」，延迟超过客户端窗口（默认 3s）就等于没回。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "延迟毫秒数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "同一 Probe 回两次")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端按 EPR 去重、同 EPR 后到覆盖先到；两份 XAddrs 不同时「最后到达那份的第一个 XAddr 胜出」。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "第二份用不同的 XAddrs")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Scopes 不含 name")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "上层只从 Scopes 读 onvif.org/name/ 与 /hardware/，缺 name 时相机显示为无名。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "建连与鉴权")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "XAddr 报非常规端口 / 路径")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "真机 TL-IPC652P-A4 报 :2020/onvif/service 而实际连的是 80。客户端只接管 host:port、保留 path，正好测这条逻辑。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "对外宣称的端口")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "对外宣称的服务路径")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "GetServices 里 Media2 排在 Media 前")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Media(ver10) 与 Media2(ver20) 的命名空间都含 /media/；只按服务名匹配的客户端会把 media 解析到 Media2 端点，然后往那儿发 ver10 的 GetProfiles 吃 ActionNotSupported。海康 / Axis 双栈固件的真实布局。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不实现 GetServices")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "老固件常见。客户端要能回落到 GetCapabilities 或约定路径。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "UsernameToken 时间窗收紧")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "参照客户端不做时钟补偿（adjust_time 从不传 True）。把 Created 允许偏差收紧再叠加时钟偏移，就能复现「全线 401」。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "允许的时间偏差（秒）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "设备时钟相对真实时间的偏移（秒）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅只增不回收")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "onvif-zeep 每次构造 ONVIFCamera 都建一条 PullPoint 订阅且从不 Unsubscribe。关掉过期回收即可复现真实高发的槽位泄漏。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "GetDeviceInformation 缺字段")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "真机常缺 HardwareId 或 SerialNumber，按这些字串选厂商适配器的客户端会落空。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "要省略的字段，逗号分隔：Manufacturer,Model,FirmwareVersion,SerialNumber,HardwareId")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "只接受 PasswordText")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "参照客户端一律发 PasswordDigest，拒绝 Digest 即全线鉴权失败。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "nonce 严格一次性")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "缓存已用 nonce，重复即 401，用来测客户端是否每次重新生成。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "nonce 缓存时长（秒）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "PRE_AUTH 操作也要鉴权")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "规范允许 GetSystemDateAndTime / GetCapabilities / GetServices / GetWsdlUrl 匿名调用；有些固件不允许。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "鉴权失败回 HTTP 401")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "规范做法是 SOAP Fault ter:NotAuthorized；有些固件直接 401 带 WWW-Authenticate: Digest。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SOAP Fault 的 HTTP 状态码")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Fault 既可能走 500 也可能走 200。客户端对 500 要放行给 body 解析。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "返回 Fault 时用的 HTTP 状态码")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "鉴权 Fault 措辞变体")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端靠关键词匹配判定认证错误：notauthorized / not authorized / unauthorized / authentication / sender not authorized / failedauthentication。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Fault 子码与措辞风格；Unknown=不含任何关键词")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Media 与快照")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "profile 命名风格")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端判定主 / 子码流只看 profile Name 是否含 main|primary|high / sub|secondary|low；Profile_1 / Profile_2 这种没有主子语义的名字会逼它按顺序猜。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "命名风格")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "StreamUri 自带 user:pass@")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端会丢弃相机返回的 userinfo 再注入自己的凭据，用来验证这段清洗逻辑。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "嵌入 URI 的 user:pass")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "URI 套在 MediaUri/Uri 下")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "响应结构多一层，只认顶层 Uri 的客户端会取空。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "StreamUri 用占位 IP")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "固件把出厂默认 IP 写死进 URI，客户端必须用 XAddr 的 host 覆盖。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "占位 host，可填 0.0.0.0")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "快照 200 + 空体")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "真踩过「200 + image/jpeg + 空体」。客户端必须按体长与魔数判定而不是状态码。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "坏响应形态")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "快照鉴权方式")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端按 Digest → Basic → 无 顺序试，且只在 401 时才换下一种。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "鉴权方式；token=URI 里带一次性令牌")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "快照 URI 定期失效")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端连续 3 次取图失败才判 URI 失效并重探，中间会盲取。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "URI 有效期（秒）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不实现 GetSnapshotUri")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "回 ActionNotSupported，客户端应退化为从码流抽帧或干脆没有快照。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "声明与实发编码不一致")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "很多家用机 capability 列了 G.711 / G.722 / AAC，backchannel SDP 却只有 PCMU。运行时必须以 SDP 为准。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "ONVIF 里声明的音频编码")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SDP 与 RTP 里实际用的编码")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "声明分辨率与码流不符")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端不读 VideoEncoderConfiguration、全靠 ffprobe 探流，这条用来测两边不一致时它信谁。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "PTZ")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "PTZConfiguration 只挂子码流")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "只看主码流 profile 的客户端会判定「没有 PTZ」。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不挂 PTZConfiguration 但 PTZ 可用")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "所有 profile 都不带 PTZConfiguration，但 GetNodes 非空且能真转。客户端应回落到 GetNodes 判定。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SupportedPTZSpaces 为空")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "能力声明四档之一：完整 / 为空 / 只有 Default*Space / 只有 pan。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "声明档位")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "PTZ Range 的 Min == Max")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "除零或退化区间会让客户端的归一化计算炸掉。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "非零 Zoom 触发畸形响应")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "真机在 ContinuousMove 带非零 Zoom 时回显请求字节 + 500。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "出厂预填 300 个预置位")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "「预置点 1..300」加巡航扫描 / 远程重启等功能槽，共享同一个假 PTZPosition。用来压客户端的预置位列表 UI。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "预置位数量")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "预置位名百分号编码")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "相机把 %E9%A2%84 这类编码原样吐回，客户端要 unquote 才显示得对。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不实现 GetPresets")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "回 ActionNotSupported，或回一段 not implemented 文本。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不支持的表现形式")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SetPreset 返回形态")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "有的固件返回裸字符串 token，有的返回带 PresetToken 的对象。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "返回形态")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "PTZ 响应延迟抖动")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "100~800ms 随机延迟，用来验证客户端的命令乱序防护。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "最小延迟")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "最大延迟")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "GotoPreset 特别慢")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "响应正常但机械动作要好几秒，GetStatus 期间一直 MOVING。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "到位耗时")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "移动不反映到 GetStatus")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "命令返回成功但 GetStatus 的 Position 永远不动，客户端无法闭环。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "事件")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅管理器换独立端口且递增")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "真机形如 :1024/event-1024_1024，下一条订阅换 :1025。客户端必须用返回的订阅地址而不是主服务地址去 Pull。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "起始端口")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅地址 host 不可达")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "固件把内网地址写进订阅 URL，客户端要么接管 host 要么彻底卡住。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "写进订阅地址的 host")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅槽位上限")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "配合 A9（只增不回收）就是真实的槽位耗尽故障。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "最大并发订阅数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "超限行为")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不实现 GetEventProperties")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端拿不到 TopicSet，只能盲订阅全部。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "GetEventProperties 返回非法 XML")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "TP-Link TL-IPC 真机返回属性值不加引号的 XML（wstop:topic=true）。客户端必须先补引号再解析。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅 Address 不套 Reference")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Address 直接放响应下，不包 SubscriptionReference 一层。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Topic 命名风格")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "标准 ONVIF / TP-Link（LineCrossDetector）/ Reolink（MyRuleDetector）/ Axis（tnsaxis: 前缀）四套。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "PullMessages 永远返回空")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅建得起来、Pull 也不报错，就是永远没有事件。最难查的一类故障。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "属性型事件不发配对的 false")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "正常应成对发 IsMotion=true / false；只发 true 会让客户端的移动侦测永远不复位。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "Renew 总是失败")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端必须能在 Renew 失败后重建订阅而不是放弃。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "订阅建完立刻过期")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "CreatePullPointSubscription 成功但 TerminationTime 已是过去时间。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "事件风暴")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每秒推 N 条事件，压客户端的队列与 UI。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每秒事件数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不支持 SetSynchronizationPoint")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端拿不到属性型 topic 的当前状态，只能等下一次变化。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "RTSP 与对讲")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "音频能力谎标")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "ONVIF 声明的解码能力与 backchannel SDP 实际开放的 codec 不一致。客户端必须以 SDP 为准。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "G.722 采样率错写成 8000")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "G.722 的 RTP 时钟率按规范写 8000 但实际是 16000，很多固件在 ONVIF 能力里也错写成 8000。客户端应强制按 16000 处理。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "码率单位变体")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "有的固件按 kbps 报，有的按 bps 报，差 1000 倍。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "码率字段单位")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "GetAudioDecoderConfigurationOptions 响应形态")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "形态 A：G711/G722/G726/AAC 子元素直挂 opts；形态 B：AudioDecoderOptions 列表，每项带 Encoding。两种都得支持。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "a=子元素直挂，b=Options 列表")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "采样率字段形态")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SampleRateRange / SampleRateList / 单值三种形态都在真机上出现过。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "字段形态")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "对讲双轨布局")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "海康是单轨（只有 sendonly 对讲轨）；大华是双轨（麦克风 recvonly 在前 + 对讲 sendonly 在后），客户端要挑对轨才推得进去。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "对讲忙槽位")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "TEARDOWN 后 N 秒内对新的 backchannel DESCRIBE 回 401。海康球机实测 3~4 秒。客户端必须重试而不是判定凭据错误。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "忙槽位持续秒数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "同时发 Basic + Digest 挑战")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "两条 WWW-Authenticate，顺序可配。有的客户端只看第一条。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "两条挑战的顺序")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "严格 Digest 参数校验")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端 Authorization 里出现挑战没给过的参数（如 algorithm=MD5）就 401。真机上很多客户端因此连不上。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SDP 声明不规范 codec")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "G7221 / G726-32 这类写法，客户端的 codec 表匹配不上要能优雅降级。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "写进 a=rtpmap 的编码名")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SDP 不写 rtpmap")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "只给静态 payload type（0=PCMU / 8=PCMA），客户端要按 RFC 3551 静态表推断。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "只有 session 级 a=control")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "媒体级没有 control 属性，客户端拼 SETUP URL 时只能用 session 级的。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "校验 talkspurt 首包 marker")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "相机要求每段话首包置 RTP marker 位，否则整段静音丢弃。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SETUP 响应不带 Session 头")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "违反 RFC 2326，客户端后续 PLAY 无 Session 可用。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "忽略 backchannel Require 头")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不带 Require 也返回含 sendonly 的 SDP，或严格按 RFC 2326 对不支持的 Require 回 551。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "ignore=不看 Require 照给，strict_551=不支持就 551")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不实现 AudioOutput/Decoder 配置")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "AddAudioOutputConfiguration / AddAudioDecoderConfiguration 整体回 ActionNotSupported，客户端只能直接开 backchannel 试。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "对讲推流期停止排空")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "相机不再读 TCP 接收缓冲，客户端的 sendall 卡死在内核缓冲区满。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "推流开始后多久停止排空")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "RTSP 并发会话上限")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "廉价相机常态：超过上限回 453 Not Enough Bandwidth。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "最大并发会话数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "周期性主动断流")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每 N 秒相机自己 TEARDOWN，客户端必须能自动重连。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "断流间隔")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "RTP 丢包")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "按比例随机丢弃 RTP 包，测客户端的花屏恢复。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "丢包率（%）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "RTP 时间戳跳变")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "周期性让时间戳大幅跳跃，测客户端的抖动缓冲。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "跳变间隔")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "跳变量（毫秒，可负）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SPS/PPS 位置")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "只在 SDP 的 sprop-parameter-sets / 只在带内 / 两处都有。只认一处的解码器会黑屏。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "放置策略")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "画面冻结")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "RTP 继续发但画面内容不变，测客户端的冻结检测。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "黑屏")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "切换到全黑样片，测客户端的黑屏检测。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "帧率突变")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "实际帧率与声明不符且中途变化。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "实际帧率")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "不发 RTCP SR")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "客户端拿不到 NTP 映射，音视频同步只能靠 RTP 时间戳硬估。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "传输与设备")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "畸形 HTTP 响应")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "回显请求原始字节 + 500，或缺 Content-Length、状态行残缺。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "畸形形式")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "触发概率（%）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "自签证书 HTTPS")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "TP-Link VIGI 的私有 API 走 20443 自签 HTTPS，客户端必须跳过证书校验。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "HTTPS 端口")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "并发过载时模拟重启")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "一秒内的 SOAP 请求数超过阈值就整机假死再回来，复现廉价固件被打挂。按速率而不是瞬时并发判定：单事件循环下请求本来就是串行处理的。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每秒请求数阈值")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "假死秒数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "SystemReboot 真的离线")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "发 Bye → 关掉全部端口 N 秒 → 发 Hello 回来，而不是只回个 OK。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "离线秒数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "随机掉线")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "按概率整机离线一小段时间，模拟不稳定的 PoE / WiFi。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每次请求触发掉线的概率（%）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每次掉线秒数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "超大响应体")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "塞进大量填充，测客户端的解析上限与内存。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "响应体大小（KB）")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "慢发送")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "响应分成小块、每块之间等一会儿，测客户端的读超时。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "每块字节数")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "块间隔")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "整机响应延迟")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "所有 HTTP 响应统一延迟，模拟远端 / 弱网相机。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "RTP 限速")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "按给定带宽发 RTP，低于码流需求就会持续积压。")),
        QStringLiteral(QT_TRANSLATE_NOOP("onvifsim::quirks", "上限带宽（kbps）")),
    };
}

} // namespace onvifsim
